version: "1"
rules:                      # Array of rules
  - base: 13.0            # Required. Target branch
    upstream: odoo:13.0    # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
